### PR TITLE
Median of 3 implementation and quicksort fixes

### PR DESCRIPTION
**Pull request by andyzhengbaige**
**This pull request features the median of 3 implementation of quicksort and some quicksort fixes.**

In this version, quicksort median of 3 and the default quicksort uses a shared module called quicksort_shared.js

The implementation focuses on toggling between the two quicksort modes and fixing the bugs related to both modes.

### CODE REVIEW

**Review by HenryRoutson — APPROVED** [review]
Looks good

**Review by rodenwild — APPROVED** [review]
LGTM

**Comment by benhsampson** [comment]
LGTM

**Review by benhsampson — APPROVED** [review]
Me likey

**Pull request merged**
